Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      IpAddressType: "ipv4"
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref ShopsSecurityGroup
      Subnets:
        - !Ref ShopsSubnet0
        - !Ref ShopsSubnet1

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Protocol: HTTP
      Port: 80
      LoadBalancerArn: !Ref LoadBalancer
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: application/json
            MessageBody: "Page Not Found"
            StatusCode: "404"
        # - Type: forward
        #   TargetGroupArn: !Ref LoadBalancerTargetGroup

  # LoadBalancerTargetGroup:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     TargetType: lambda
  #     Targets:
  #       - AvailabilityZone: all
  #         Id: !GetAtt shops.Arn
